import { hbs } from 'ember-cli-htmlbars';
const icons = [
  "add",
  "alert-triangle",
  "archive",
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "attachment",
  "bin",
  "bold",
  "book",
  "calendar-new",
  "calendar",
  "caret-down",
  "caret-up-down",
  "caret-up",
  "check",
  "checkbox-checked",
  "checkbox-indeterminate",
  "checkbox-unchecked",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "circle-check",
  "circle-full",
  "circle-info",
  "circle-pause",
  "circle-question",
  "circle-step-1",
  "circle-step-2",
  "circle-step-3",
  "circle-step-4",
  "circle-step-5",
  "circle-step-6",
  "circle-three-dots",
  "circle-x",
  "circle",
  "clock-rewind",
  "clock",
  "comment",
  "copy-paste",
  "copy",
  "cross",
  "dash",
  "document-added",
  "document",
  "documents",
  "download",
  "draft",
  "drag-handle-2",
  "drag-handle",
  "drag",
  "expand-vertical",
  "expand",
  "export",
  "external-link",
  "external",
  "eye",
  "file",
  "filter",
  "folder",
  "gear",
  "github",
  "hierarchal-back",
  "hierarchical-back",
  "html-dot",
  "html-plus",
  "html",
  "import",
  "indent",
  "info-circle",
  "italic",
  "label",
  "link-broken",
  "link-external",
  "link",
  "lock-closed",
  "lock-open",
  "login",
  "logout",
  "mail",
  "manual",
  "message",
  "minimize",
  "nav-down",
  "nav-left",
  "nav-right",
  "nav-up-down",
  "nav-up",
  "no-sign",
  "not-visible",
  "ordered-list",
  "paperclip",
  "pdf-dot",
  "pdf-plus",
  "pdf",
  "pencil",
  "plus-text",
  "plus",
  "printer-view",
  "printer",
  "question-circle",
  "redo",
  "remove",
  "renew",
  "reverse-indent",
  "search-folder",
  "search",
  "settings",
  "sign",
  "signinghub",
  "sitemap",
  "strikethrough",
  "switch",
  "synchronize",
  "three-dots",
  "trash",
  "underlined",
  "unordered-list",
  "upload",
  "user-add",
  "user-check",
  "user-fill",
  "user-popup",
  "user",
  "users",
  "visible",
  "word-dot",
  "word-plus",
  "word",
  "x",
]

export default {
  title: 'Components/Links/AuLink',
  argTypes: {
    text: {control: 'text', description:''},
    route: {control: 'route', description:'The route that is passed to the link'},
    skin: { control: 'select', options: ['primary', 'secondary', 'button', 'button-secondary'], description:'Defines the style of the link'},
    icon: { control: 'select', options: icons, description:'Adds an icon'},
    iconAlignment: { control: 'select', options: ["left","right"], description:'hoose the position of the icon, adds correct margin next to the icon'},
    hideText: { control: 'boolean',  description:'Hides the link text visually'},
    width: { control: 'select', options: ["","block"], description:'Defines the width of the link'},
    active: { control: 'boolean', description:'Adds an active state and disables pointer events'},
    model: { control: 'model', description:'Supply a model to the route'},
    models: { control: 'model', description:'Supply models to the route'},
    query: { control: 'query', description:'Supply query parameters to the route'},
  },
  parameters: {
    layout: 'padded',
  },
};

const Template = (args) => ({
  template: hbs`
    <AuLink
      @route={{this.route}}
      @skin={{this.skin}}
      @icon={{this.icon}}
      @iconAlignment={{this.iconAlignment}}
      @hideText={{this.hideText}}
      @width={{this.width}}
      @active={{this.active}}
      @model={{this.model}}
      @models={{this.models}}
      @query={{this.query}}
    >
      {{text}}
    </AuLink>`,
  context: args,
});

export const Component = Template.bind({});
Component.args = {
  text: "Link",
  route: "index",
  skin: "primary",
  icon: "login",
  iconAlignment: "left",
  hideText: false,
  width: "",
  active: false
};
